name: set-environment
author: EleSangwon
inputs:
  ref:
    description: ''
    required: false
    default: 'dev'
  head_ref:
    description: ''
    required: false
    default: 'hotfix'
  type:
    description: ''
    required: false
    default: 'branch'
outputs:
  deploy_env:
    description: 'Get deployed environment'
    value: ${{ steps.val.outputs.deploy_env }}
runs:
  using: "composite"
  steps:
    - name: Check Ref
      id: val
      shell: bash
      run: |
        QA_TAG='v+[0-9].+[0-9].+[0-9]-rc.+[0-9]+'
        TYPE=${{ inputs.type }}
        REF_NAME=${{ inputs.ref }}
        HEAD_REF_NAME=${{ inputs.head_ref }}
        echo ::set-output name=deploy_env::$( echo dev )
        if [[ "${TYPE}" == "tag" ]]; then
          if [[ "${REF_NAME}" =~ "${QA_TAG}" ]]; then
            echo ::set-output name=deploy_env::$( echo qa )
          fi
        elif [[ "${TYPE}" == "branch" ]]; then
          if [[ "${REF_NAME}" =~ "hotfix" ]]; then
            echo ::set-output name=deploy_env::$( echo qa )
          elif [[ "${REF_NAME:0:6}" == "master" ]]; then
            echo ::set-output name=deploy_env::$( echo staging )
          fi
        fi
        if [[ "${HEAD_REF_NAME}" =~ "hotfix" ]]; then
          echo ::set-output name=deploy_env::$( echo qa )
        fi