name: assume-role
author: EleSangwon
inputs:
  region:
    description: 'aws region'
    required: false
    default: 'ap-northeast-1'
  aws-role-arn:
    description: 'aws role arn'
    required: true
    default: ''
  role-session-name:
    description: 'aws assume role session name'
    required: false
    default: 'SessionForGithubActions'
  duration:
    description: 'session duration time. default is 30 mins'
    required: false
    default: '3600'
runs:
  using: "composite"
  steps:
    - name: check the session name length
      shell: bash
      id: val
      run: |
        SESSION=${{ inputs.role-session-name }}
        NAME=${SESSION:0:63}
        echo "::set-output name=SESSION_NAME::$(echo $NAME)"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        aws-role-arn: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ steps.val.outputs.SESSION_NAME }}
        role-duration-seconds: ${{ inputs.duration }}